package Beans;
// Generated Mar 22, 2016 10:27:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer bookId;
     private Category category;
     private String bookName;
     private Integer quantity;
     private String author;
     private int price;
     private String img;
     private String description;
     private Set cartBooks = new HashSet(0);

    public Book() {
    }

	
    public Book(String bookName, int price) {
        this.bookName = bookName;
        this.price = price;
    }
    public Book(Category category, String bookName, Integer quantity, String author, int price, String img, String description, Set cartBooks) {
       this.category = category;
       this.bookName = bookName;
       this.quantity = quantity;
       this.author = author;
       this.price = price;
       this.img = img;
       this.description = description;
       this.cartBooks = cartBooks;
    }
   
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getCartBooks() {
        return this.cartBooks;
    }
    
    public void setCartBooks(Set cartBooks) {
        this.cartBooks = cartBooks;
    }




}


