package Beans;
// Generated Mar 22, 2016 10:27:26 PM by Hibernate Tools 4.3.1



/**
 * CartBook generated by hbm2java
 */
public class CartBook  implements java.io.Serializable {


     private CartBookId id;
     private Book book;
     private Cart cart;
     private int bookQuantity;

    public CartBook() {
    }

    public CartBook(CartBookId id, Book book, Cart cart, int bookQuantity) {
       this.id = id;
       this.book = book;
       this.cart = cart;
       this.bookQuantity = bookQuantity;
    }
   
    public CartBookId getId() {
        return this.id;
    }
    
    public void setId(CartBookId id) {
        this.id = id;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public int getBookQuantity() {
        return this.bookQuantity;
    }
    
    public void setBookQuantity(int bookQuantity) {
        this.bookQuantity = bookQuantity;
    }

}


