package Beans;
// Generated Mar 22, 2016 10:27:26 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String email;
     private String userName;
     private String password;
     private BigDecimal creditLimit;
     private String job;
     private String address;
     private String photo;
     private String role;

    public User() {
    }

	
    public User(String email, String userName, String password, BigDecimal creditLimit) {
        this.email = email;
        this.userName = userName;
        this.password = password;
        this.creditLimit = creditLimit;
    }
    public User(String email, String userName, String password, BigDecimal creditLimit, String job, String address, String photo, String role) {
       this.email = email;
       this.userName = userName;
       this.password = password;
       this.creditLimit = creditLimit;
       this.job = job;
       this.address = address;
       this.photo = photo;
       this.role = role;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public BigDecimal getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


